name: test_dart_package
description: A starting point for Dart libraries or applications.
version: 0.0.4
homepage: https://github.com/dendysatrya/test-dart-package/
repository: https://github.com/dendysatrya/test-dart-package/

false_secrets:
  - /credentials.json

environment:
  sdk: ">=2.19.2 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
